language: csharp
solution: "./Source/Epsylon.TextureSquish.sln"

before_script:
  - dotnet restore "./Source/Epsylon.TextureSquish.sln"

after_script:
  - dotnet test "Sources/Epsylon.TextureSquish.UnitTests/Epsylon.TextureSquish.UnitTests.csproj"